### ISSUE TITLE
run test and produce "Cannot find module 'worker_threads'"

### ISSUE THREAD

**Issue by luckhpy** [codeceptjs/CodeceptJS#2763]
version: 3.0.4，it's ok in 2.6.6

```bash
 npx codeceptjs run --steps -c
```

**Comment by PeterNgTr** [comment]
hey @luckhpy did you run with node version > 11?

**Comment by mksmtn** [comment]
I had the same issue with node v10. After upgrading to v15 it's gone

**Comment by PeterNgTr** [comment]
To use run-workers command, please just use v11+.

**Comment by ngraf** [comment]
@PeterNgTr 
What about raising dependency in "package.json" to NodeJS 11.7 to make this dependency more clear?

https://github.com/codeceptjs/CodeceptJS/blob/d755c1555ae67592e8dc2e6331d3bd4c82e246bc/package.json#L143

We had same issue in Slack with `npx codeceptjs init`
https://codeceptjs.slack.com/archives/C94G8JXJB/p1617894507357600

I wonder if there are disadvantages. Probably for people who don't want/have to run with old NodeJS and don't want to use "worker_threads"? But then I would still expect that at least `npx codeceptjs init` works on old NodeJS versions.
